on: 
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    - name: Composer Install
      run: composer install --no-dev --no-scripts
    - name: Composer Update
      run: composer update
    - name: Cache Clear
      run: php artisan cache:clear
    - name: Config Clear
      run: php artisan config:clear
    - name: Route Clear
      run: php artisan route:clear
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.coolkapada.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /public_html/../coolkapada/
    